#!/usr/bin/env python3
"""
把灰度/彩色图转成 e-paper 用的 1-bit C 数组头文件。

用法:
  python3 tools/img2bitmap.py assets/cartoon_src.jpg \
    --out drafts/home_v1/cartoon.h --name cartoon \
    --size 150 --dither floyd

输出的 .h 文件里有:
  - extern const uint8_t cartoon_bitmap[];   // 1-bit packed,每 byte 装 8 像素,MSB 在左
  - constexpr int cartoon_w = 150;
  - constexpr int cartoon_h = 150;

直接喂给 Adafruit_GFX 的 drawBitmap(x, y, cartoon_bitmap, w, h, color)。
"""
import argparse
from pathlib import Path
from PIL import Image, ImageOps, ImageEnhance, ImageFilter


def make_mask(src: Path, size: int, fit: bool, mask_cutoff: int,
              dilate: int) -> Image.Image:
    """生成"卡通主体形状"蒙版:主体=黑(bit=1,不透明),padding=白(bit=0,透明)。"""
    img = Image.open(src).convert("L")
    img = ImageOps.autocontrast(img, cutoff=2)
    if fit:
        img = ImageOps.fit(img, (size, size), centering=(0.5, 0.5))
    else:
        img = ImageOps.contain(img, (size, size))
        canvas = Image.new("L", (size, size), 255)
        ox = (size - img.width) // 2
        oy = (size - img.height) // 2
        canvas.paste(img, (ox, oy))
        img = canvas
    # 阈值化:任何"非纯白"灰度都算主体
    mask = img.point(lambda v: 0 if v >= mask_cutoff else 255, mode='L')
    # 形态学膨胀:让主体边缘外扩 dilate 像素,保证擦白时不留残边
    if dilate > 0:
        ksize = dilate * 2 + 1
        mask = mask.filter(ImageFilter.MaxFilter(ksize))
    # 再反相,让"主体=黑、padding=白",这样后续 pack_1bit 时主体 bit=1
    mask = ImageOps.invert(mask)
    return mask.convert("1", dither=Image.Dither.NONE)


def to_1bit(src: Path, size: int, dither: str, invert: bool,
            bg_cutoff: int, autocontrast: bool, threshold: int,
            contrast: float, blur: float, fit: bool) -> Image.Image:
    img = Image.open(src).convert("L")              # 转灰度
    if invert:
        img = ImageOps.invert(img)
    if autocontrast:
        img = ImageOps.autocontrast(img, cutoff=2)  # 拉满动态范围,前 2% 极值丢弃
    if contrast != 1.0:
        img = ImageEnhance.Contrast(img).enhance(contrast)
    # 把高于 bg_cutoff 的像素强制变白(去掉浅灰背景),其余保留
    if bg_cutoff < 255:
        img = img.point(lambda v: 255 if v >= bg_cutoff else v)
    if blur > 0:
        img = img.filter(ImageFilter.GaussianBlur(radius=blur))

    if fit:
        # 直接裁剪到方形,主体居中。padding 极少
        canvas = ImageOps.fit(img, (size, size), centering=(0.5, 0.5))
    else:
        # 等比缩放后用白色补成方形,周围有 padding
        img = ImageOps.contain(img, (size, size))
        canvas = Image.new("L", (size, size), 255)
        ox = (size - img.width) // 2
        oy = (size - img.height) // 2
        canvas.paste(img, (ox, oy))

    if dither == "floyd":
        out = canvas.convert("1", dither=Image.Dither.FLOYDSTEINBERG)
    elif dither == "none":
        out = canvas.point(lambda v: 0 if v < threshold else 255, mode="1")
    else:
        raise ValueError(f"unknown dither: {dither}")
    return out


def pack_1bit(img: Image.Image) -> bytes:
    """每 byte 装 8 像素,MSB 是最左边的像素;'0' 表示黑、'1' 表示白。
    Adafruit_GFX::drawBitmap 默认: bit=1 画 color,bit=0 不画(留底)。
    我们让 bit=1 表示需要画黑像素,所以反过来。"""
    w, h = img.size
    out = bytearray()
    px = img.load()
    for y in range(h):
        bit = 0
        byte = 0
        for x in range(w):
            v = px[x, y]            # 0 黑 / 255 白
            if v == 0:
                byte |= (1 << (7 - bit))
            bit += 1
            if bit == 8:
                out.append(byte)
                bit = 0
                byte = 0
        if bit:                     # 行末不足 8 位,补齐
            out.append(byte)
    return bytes(out)


def emit_header(name: str, data: bytes, w: int, h: int) -> str:
    lines = []
    lines.append(f"// Auto-generated by tools/img2bitmap.py. DO NOT EDIT.")
    lines.append(f"// {w}x{h}, 1-bit, MSB-left, bit=1 表示黑像素")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("#include <pgmspace.h>")
    lines.append("")
    lines.append(f"constexpr int {name}_w = {w};")
    lines.append(f"constexpr int {name}_h = {h};")
    lines.append(f"const uint8_t {name}_bitmap[{len(data)}] PROGMEM = {{")
    chunk = []
    for i, b in enumerate(data):
        chunk.append(f"0x{b:02X}")
        if (i + 1) % 16 == 0:
            lines.append("  " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("  " + ", ".join(chunk) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("src", type=Path, help="源图,任意格式 (JPG/PNG/...)")
    p.add_argument("--out", type=Path, required=True, help="输出 .h 文件路径")
    p.add_argument("--name", default="img", help="C 标识符前缀")
    p.add_argument("--size", type=int, default=150, help="正方形输出边长")
    p.add_argument("--dither", choices=["floyd", "none"], default="floyd")
    p.add_argument("--invert", action="store_true", help="反相 (深底浅卡通时用)")
    p.add_argument("--bg-cutoff", type=int, default=220,
                   help="高于此灰度的像素强制变纯白 (清浅色背景),0-255,255 表示不清理")
    p.add_argument("--no-autocontrast", action="store_true",
                   help="跳过自动对比度拉伸 (默认开启,可让暗部更暗、亮部更亮)")
    p.add_argument("--threshold", type=int, default=128,
                   help="dither=none 时的二值化阈值,低于此值算黑")
    p.add_argument("--contrast", type=float, default=1.0,
                   help="对比度增强倍率 (>1 更对比强,1=不动);抖动前生效,可让灰阶向两端聚拢减少噪点")
    p.add_argument("--blur", type=float, default=0.0,
                   help="抖动前的高斯模糊半径 (像素),软化细节让抖动模式更连续")
    p.add_argument("--fit", action="store_true",
                   help="用 ImageOps.fit 自动裁剪到方形(主体放大、padding 少);不指定则用 contain 留白边")
    p.add_argument("--preview", type=Path, help="同时保存一张 PNG 预览图,方便人眼检查")
    p.add_argument("--mask-out", type=Path,
                   help="同时生成主体形状蒙版 .h (主体=bit1,padding=bit0),用于擦白叠加")
    p.add_argument("--mask-cutoff", type=int, default=235,
                   help="mask 阈值:低于此值算主体")
    p.add_argument("--mask-dilate", type=int, default=2,
                   help="mask 形态学膨胀像素数,让主体边缘外扩防漏边")
    p.add_argument("--mask-preview", type=Path, help="mask 的 PNG 预览图")
    p.add_argument("--clip-by-mask", action="store_true",
                   help="生成 cartoon.h 后再用 mask 做一次裁切 (mask 外的像素强制变白,清影子)")
    args = p.parse_args()

    img = to_1bit(args.src, args.size, args.dither, args.invert,
                  args.bg_cutoff, not args.no_autocontrast, args.threshold,
                  args.contrast, args.blur, args.fit)
    if args.preview:
        img.save(args.preview)
        print(f"preview saved: {args.preview}")

    data = pack_1bit(img)
    text = emit_header(args.name, data, img.width, img.height)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"wrote {args.out}: {img.width}x{img.height}, {len(data)} bytes")

    if args.mask_out:
        mask_img = make_mask(args.src, args.size, args.fit,
                             args.mask_cutoff, args.mask_dilate)
        if args.mask_preview:
            mask_img.save(args.mask_preview)
            print(f"mask preview saved: {args.mask_preview}")

        # 按 mask 裁切 cartoon:mask 外的所有像素强制变白,
        # 让影子/噪点自动清掉,但 cartoon 主体保留原本的灰阶/抖动细节
        if args.clip_by_mask:
            # mask_img 是 mode='1',pixel 值是 0 (主体) 或 255 (背景)
            # 把背景区域内的 cartoon 像素强制变 1 (白)
            from PIL import Image as _Image
            cartoon_pixels = img.load()
            mask_pixels = mask_img.load()
            for yy in range(img.height):
                for xx in range(img.width):
                    if mask_pixels[xx, yy] != 0:   # mask=背景
                        cartoon_pixels[xx, yy] = 1  # 强制白
            # 重新打包 cartoon
            data = pack_1bit(img)
            text = emit_header(args.name, data, img.width, img.height)
            args.out.write_text(text)
            print(f"re-wrote {args.out} after mask clip")
            if args.preview:
                img.save(args.preview)

        mask_data = pack_1bit(mask_img)
        mask_name = args.name + "_mask"
        mask_text = emit_header(mask_name, mask_data, mask_img.width, mask_img.height)
        args.mask_out.parent.mkdir(parents=True, exist_ok=True)
        args.mask_out.write_text(mask_text)
        print(f"wrote {args.mask_out}: {mask_img.width}x{mask_img.height}, {len(mask_data)} bytes")


if __name__ == "__main__":
    main()
